# DEPLOY TO PRODUCTION github action

name: Deploy to production

# on dispatch event from github UI
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard openresolv
          echo "${{ secrets.VPN_CONF }}" | base64 -d > /tmp/wg0.conf
          sudo mv /tmp/wg0.conf /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: jnroot
          server: ${{ secrets.FTP_SERVER }}
          local_path: './dist/*'
          remote_path: '/var/www/html'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
          ssh_private_key: ''
      - name: Disconnect WireGuard
        run: sudo wg-quick down wg0
